# Generated by Django 4.1.3 on 2022-12-29 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_password1_users_password2_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='users',
            name='surname',
        ),
    ]
