# Generated by Django 4.1.3 on 2022-12-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_pict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='pict',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
