# Generated by Django 4.1.3 on 2022-12-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_pict_pict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='pict',
            field=models.ImageField(null=True, upload_to='templates/images'),
        ),
    ]
