# Generated by Django 4.1.3 on 2022-12-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_pict_pict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='pict',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
