# Generated by Django 4.1.3 on 2023-01-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_pict_pict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='pict',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
