# Generated by Django 4.1.3 on 2023-01-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_pict_pict'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pict',
        ),
    ]
